import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner"
import { CookiesProvider } from 'next-client-cookies/server';
import AuthProvider from '@/context/AuthProvider'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CookiesProvider>
      <html lang="en">
        <AuthProvider>
          <body className={inter.className}>
            <div className="md:px-20">
              <Header></Header>
              {children}
            </div>
            <Footer/>
            <Toaster />
          </body>
        </AuthProvider>
      </html>
    </CookiesProvider>
  );
}
